---

services:

  app:
    image: europe-southwest1-docker.pkg.dev/nakanodo-main/nakanodo/github-readme-stats:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    platform: linux/amd64
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    env_file:
      - .env
